language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - 'node_modules'
after_success: npm run coverage

notifications:
  email: false

services:
  - postgresql

env:
  - NODE_ENV=test
  - USER=abiodun
  - DATABASE=travis_ci_test
  - PASSWORD=olaTUNDELA234
  - PORT=5432

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c "create user abiodun with password 'olaTUNDELA234';" -U postgres
  - psql -U abiodun travis_ci_test < test/testdata.sql
