language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - 'node_modules'
after_success: npm run coverage

notifications:
  email: false

services:
  - postgresql

env:
- NODE_ENV=test

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c 'CREATE USER root WITH PASSWORD 'olaTUNDELA234';" -U postgres
  - psql -U root travis_ci_test < test/testdata.sql